version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo "Installing dependencies..."
      - npm install
      - npm install -g @angular/cli@10.0.8
  build:
    commands:
      - echo "Building Angular project..."
      - npm install react-scripts
      - npm run build
  post_build:
    commands:
      - echo "Copying artifacts to S3"
      - aws s3 ls
      - aws s3 cp /codebuild/* s3://abnewwwww/artifact-dev --recursive
