version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo "Installing dependencies..."
      - npm install
      - npm install -g @angular/cli@10.0.8
  build:
    commands:
      - echo "Building Angular project..."
      - npm install react-scripts
      - npm run build
  post_build:
    commands:
      - aws s3 cp /codebuild/output/ s3://abnewwwww/artifact-dev/
      - echo "Artifact uploaded to S3"
