version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo "Installing dependencies..."
      - npm install
      - npm install -g @angular/cli@10.0.8
  build:
    commands:
      - echo "Building Angular project..."
      - npm install react-scripts
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: 'dist'
  name: 'artifact-dev'
  discard-paths: yes  

  post_build:
    commands:
      - echo "Copying artifacts to S3"
      - cd dist
      - ls -al
      - aws s3 cp . s3://abnewwwww/artifact-dev --recursive
